apiVersion: spaces.upbound.io/v1beta1
kind: ControlPlane
metadata:
  name: controlplane-consumer-services-prod
  namespace: consumer-services
  labels:
    acmeco/team: consumer-services
    acmeco/environment: prod
spec:
  crossplane:
    autoUpgrade:
      channel: Stable 
  writeConnectionSecretToRef:
    name: kubeconfig-controlplane-consumer-services-prod
    namespace: consumer-services